import { cn } from "@/lib/utils";
import { FileText, Users, TrendingUp, Award, BarChart2, BookOpen, Download } from "lucide-react";

const REPORT_CARDS = [
  { icon: FileText, title: "Attendance Summary", desc: "Daily, weekly and monthly attendance breakdown by class and student." },
  { icon: TrendingUp, title: "Fee Collection Report", desc: "Summary of fees collected, pending dues, and overdue accounts." },
  { icon: Award, title: "Student Progress Report", desc: "Academic performance trends across terms for individual students." },
  { icon: Users, title: "Teacher Performance", desc: "Attendance, assignments issued, and marks entry completion per teacher." },
  { icon: BarChart2, title: "Class-wise Results", desc: "Aggregate exam results with pass/fail ratios and top performers per class." },
  { icon: BookOpen, title: "Admission Register", desc: "Complete list of admitted students with date, class, and contact details." },
];

const RECENT = [
  { name: "Attendance Summary", by: "Admin Sharma", date: "Magh 28, 2081" },
  { name: "Fee Collection Report", by: "Admin Sharma", date: "Magh 25, 2081" },
  { name: "Class-wise Results – Class 10", by: "Suresh Paudel", date: "Magh 20, 2081" },
  { name: "Student Progress Report – Class 9A", by: "Nabin Thapa", date: "Magh 18, 2081" },
];

export default function Reports() {
  return (
    <div className="p-6 space-y-5">
      <div>
        <h1 className="text-xl font-bold text-gray-900">Reports</h1>
        <p className="text-sm text-gray-500 mt-0.5">Generate and download school reports</p>
      </div>

      <div className="grid grid-cols-3 gap-4">
        {REPORT_CARDS.map((r) => (
          <div key={r.title} className="bg-white rounded-2xl border border-gray-100 p-5 flex flex-col gap-3">
            <div className="bg-blue-50 rounded-xl p-2.5 w-fit">
              <r.icon size={18} className="text-blue-600" />
            </div>
            <div className="flex-1">
              <h3 className="font-semibold text-gray-900 text-sm">{r.title}</h3>
              <p className="text-xs text-gray-500 mt-1 leading-relaxed">{r.desc}</p>
            </div>
            <button className="bg-blue-600 text-white rounded-xl px-4 py-2 text-sm font-medium hover:bg-blue-700 w-full">
              Generate
            </button>
          </div>
        ))}
      </div>

      <div className="bg-white rounded-2xl border border-gray-100 overflow-hidden">
        <div className="px-5 py-4 border-b border-gray-100">
          <h2 className="text-sm font-semibold text-gray-700">Recently Generated</h2>
        </div>
        <table className="w-full text-sm">
          <thead className="bg-gray-50">
            <tr>
              {["Report Name", "Generated By", "Date", ""].map((h) => (
                <th key={h} className="text-left px-5 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wide">{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {RECENT.map((r, i) => (
              <tr key={i} className="border-t border-gray-50 hover:bg-gray-50/60">
                <td className="px-5 py-3.5 font-medium text-gray-900">{r.name}</td>
                <td className="px-5 py-3.5 text-gray-600">{r.by}</td>
                <td className="px-5 py-3.5 text-gray-500">{r.date}</td>
                <td className="px-5 py-3.5">
                  <button className="flex items-center gap-1.5 text-xs text-blue-600 font-medium hover:underline">
                    <Download size={12} />
                    Download
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
